---
title: "scANVI"
output: html_document
---

`
https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scvi_in_R.html

<<<<<<< HEAD
Sys.setenv(RETICULATE_PYTHON = "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

=======
>>>>>>> 310888181e79b48768c1c925763ee30d4a6c9d20
```{r}
install.packages("Seurat")
install.packages("reticulate")
install.packages("cowplot")
install.packages("devtools")
devtools::install_github("satijalab/seurat-data")
SeuratData::InstallData("pbmc3k")
install.packages("https://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.0.0.tar.gz", repos = NULL, type = "source")
SeuratData::InstallData("ifnb")
install.packages("SeuratObject")
```

```{r}
library(Seurat)
library(SeuratData)
#devtools::install_github('satijalab/seurat-data')
library(reticulate)
#devtools::install_github("cellgeni/sceasy")
library(sceasy)
```

```{r}
Rett <- load("/Users/kellychau/Desktop/05_Human_rett_corrected2.RData")
Rett = experiment.aggregate
reference <- load("/Users/kellychau/Desktop/human_Hodge_et_al.rda")
reference = human

Rett <- load("/Users/osman/Desktop/LaSalle_lab/Human_rett_data/NovaSeq_data/05_Human_rett_corrected2.RData")
Rett = experiment.aggregate
reference <- load("/Users/osman/Desktop/LaSalle_lab/Human_rett_data/NovaSeq_data/human_Hodge_et_al.rda")
reference = human
```

```{r}
print(Rett)
print(reference)
```


```{r}
reference <- FindVariableFeatures(reference, selection.method = "vst", nfeatures = 2000)
top2000 <- head(VariableFeatures(reference), 2000)
reference <- reference[top2000]

print(reference) # Seurat object
```


```{r}
library(reticulate)
library(sceasy)

sc <- import("scanpy", convert = FALSE)
scvi <- import("scvi", convert = FALSE)
```


```{r}
adata <- convertFormat(reference, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata) # Note generally in Python, dataset conventions are obs x var
```

```{r}
# run setup_anndata
scvi$model$SCVI$setup_anndata(adata)

# create the model
model = scvi$model$SCVI(adata)

# train the model
model$train(max_epochs = as.integer(2))

# to specify the number of epochs when training:
# model$train(max_epochs = as.integer(400))

```

```{r}
# get the latent represenation
latent = model$get_latent_representation()

# put it back in our original Seurat object
latent <- as.matrix(latent)
rownames(latent) = colnames(reference)
reference[["scvi"]] <- CreateDimReducObject(embeddings = latent, key = "scvi_", assay = DefaultAssay(reference))
```

```{r}
# Find clusters, then run UMAP, and visualize

reference <- FindNeighbors(reference, dims = 1:10, reduction = "scvi")
reference <- FindClusters(reference, resolution =1)

reference <- RunUMAP(reference, dims = 1:10, reduction = "scvi", n.components = 2)

DimPlot(reference, reduction = "umap", pt.size = 3)
```


```{r}
adata$obs$insert(adata$obs$shape[1], "seurat_clusters", reference[["seurat_clusters"]][,1])
```

```{r}
DE <- model$differential_expression(adata, groupby="seurat_clusters", group1 = "1", group2 = "2")

```
```{r}
print(DE$head())
```


```{r}
Rett <- FindVariableFeatures(Rett, selection.method = "vst", nfeatures = 2000)
top2000 <- head(VariableFeatures(Rett), 2000)
Rett <- Rett[top2000]

```

```{r}
adata <- convertFormat(Rett, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata)
```

```{r}
adata
```

```{r}
# run setup_anndata, use column stim for batch
scvi$model$SCVI$setup_anndata(adata, batch_key = 'orig.ident')

# create the model
model = scvi$model$SCVI(adata)

# train the model
model$train(max_epochs = as.integer(2))

# to specify the number of epochs when training:
# model$train(max_epochs = as.integer(400))
```

```{r}

# get the latent represenation
latent = model$get_latent_representation()

# put it back in our original Seurat object
latent <- as.matrix(latent)
rownames(latent) = colnames(Rett)
Rett[["scvi"]] <- CreateDimReducObject(embeddings = latent, key = "scvi_", assay = DefaultAssay(Rett))
```

```{r}
library(cowplot)
# for jupyter notebook
options(repr.plot.width=10, repr.plot.height=8)

Rett <- RunUMAP(Rett, dims = 1:10, reduction = "scvi", n.components = 2)
p1 <- DimPlot(Rett, reduction = "umap", group.by = "seurat_clusters", pt.size=2)
plot_grid(p1)
```





```{r}
#do reference first
Rett <- FindVariableFeatures(Rett, selection.method = "vst", nfeatures = 2000)
Retttop2000 <- head(VariableFeatures(Rett), 2000)
Rett <- Rett[Retttop2000]
print(Rett)
```

```{r}
sc <- import("scanpy", convert = FALSE)
scvi <- import("scvi", convert = FALSE)
```


```{r}
adata <- convertFormat(Rett, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata)
```

```{r}
# run setup_anndata
scvi$model$SCVI$setup_anndata(adata)
```

```{r}
# create the model
model = scvi$model$SCVI(adata)
```

```{r}
# train the model
model$train(max_epochs = as.integer(2))

# to specify the number of epochs when training:
# model$train(max_epochs = as.integer(400))
```

```{r}
# get the latent represenation
latent = model$get_latent_representation()

# put it back in our original Seurat object
latent <- as.matrix(latent)
rownames(latent) = colnames(Rett)
Rett[["scvi"]] <- CreateDimReducObject(embeddings = latent, key = "scvi_", assay = DefaultAssay(Rett))
```


```{r}
# Find clusters, then run UMAP, and visualize
Rett <- FindNeighbors(Rett, dims = 1:10, reduction = "scvi")
Rett <- FindClusters(Rett, resolution =1)

Rett <- RunUMAP(Rett, dims = 1:10, reduction = "scvi", n.components = 2)

DimPlot(Rett, reduction = "umap", pt.size = 3)
```

```{r}
#Error
#adata$obs$insert(adata$obs$shape[1], "seurat_clusters", Rett[["seurat_clusters"]][,1])
#adata$obs$insert(adata$obs$s)
```

```{r}
DE <- model$differential_expression(adata, groupby="seurat_clusters", group1 = "1", group2 = "2")
#Test2
```

```{r}
print(DE$head())
```


```{r}
reference <- FindVariableFeatures(reference, selection.method = "vst", nfeatures = 2000)
top2000_reference <- head(VariableFeatures(reference), 2000)
reference <- reference[top2000_reference]
```

```{r}
adata <- convertFormat(reference, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata)
```

```{r}
adata
```

```{r}

# run setup_anndata, use column stim for batch
scvi$model$SCVI$setup_anndata(adata, batch_key = 'stim')

# create the model
model = scvi$model$SCVI(adata)

# train the model
model$train(max_epochs = as.integer(2))

# to specify the number of epochs when training:
# model$train(max_epochs = as.integer(400))
```

```{r}
# get the latent represenation
latent = model$get_latent_representation()

# put it back in our original Seurat object
latent <- as.matrix(latent)
rownames(latent) = colnames(reference)
reference[["scvi"]] <- CreateDimReducObject(embeddings = latent, key = "scvi_", assay = DefaultAssay(reference))

```

```{r}
library(cowplot)
# for jupyter notebook
options(repr.plot.width=10, repr.plot.height=8)

reference <- RunUMAP(reference, dims = 1:10, reduction = "scvi", n.components = 2)
p1 <- DimPlot(reference, reduction = "umap", group.by = "stim", pt.size=2)
plot_grid(p1)

```

```{r}
options(repr.plot.width=12, repr.plot.height=10)

FeaturePlot(reference, features = c("SELL", "CREM", "CD8A", "GNLY", "CD79A", "FCGR3A",
    "CCL2", "PPBP"), min.cutoff = "q9")

```

```{r}
FeaturePlot(reference, features = c("GNLY", "IFI6"), split.by = "stim", max.cutoff = 3,
    cols = c("grey", "red"))
```